---
title: What is modularity?
author: ''
date: '2021-10-06'
slug: what-is-modularity
categories:
- papers
- journal club
- modularity
- evolvability
tags: []
subtitle: ''
summary: ''
authors: [admin]
lastmod: '2021-10-06T14:00:22-04:00'
featured: no
image:
  caption: ''
  focal_point: ''
  preview_only: yes
projects: []
bibliography: [references.bib]
csl: apa-numeric-superscript
---

Modularity is a quite general organizational pattern, and it's a useful concept in several different areas, from computer science to biology. In biology, the concept is applied at practically every level or organization, from the structure of macro-molecules (Ancel and Fontana's classic paper [@Ancel2000-vt] is probably my favorite on this subject), to ecological communities [@Grilli2016-ca]. The basic premise is the same in all these flavors of modularity: a system is modular if it's constitutive elements are organized into semi-independent groups that are internally strongly connected, leading to a internal coherence of the modules and a relative independence between modules. Influenced by [Tiago](https://skewed.de/tiago), I've recently taken to calling these modules _assortative_[@Zhang2020-up], to differentiate them from other possibilities for parceling elements into groups.
